// Code generated by assets compiler. DO NOT EDIT.
	
package main

var (
	luaLibs = map[string]string{
"/util.lua": "local Seq = {}\nSeq.__index = Seq\n\nfunction Seq.new(base)\n    return setmetatable({_n = base or 0}, Seq)\nend\n\nfunction Seq:head()\n    return self._n\nend\n\nfunction Seq:next()\n    self._n = self._n + 1\n    return self._n\nend\n\nfunction Seq:rand()\n    return math.random(self._n)\nend\n\nlocal Range = {}\nRange.__index = Range\n\nfunction Range.new(min, max)\n    max = max or 0\n    if min > max then\n        min, max = min, max\n    end\n    return setmetatable({min = min, max = max}, Range)\nend\n\nfunction Range:randi()\n    return self.min + math.random(0, self.max - self.min)\nend\n\nfunction Range:randf()\n    return self.min + (self.max - self.min) * math.random()\nend\n\nfunction Range:randt()\n    return timef(self:randi())\nend\n\nfunction choice(items)\n    return items[math.random(#items)]\nend\n\nreturn {\n    seq = Seq.new,\n    range = Range.new,\n    choice = choice,\n}\n",
}
)